# Generated by Django 5.2.4 on 2025-07-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_occ', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
    ]
